Repository 4Ailen/frontend, pull requests merged in 2023-08, with the labels that each got.

#86 Fix/#85 server changes
  lib/apis/apis.dart
  lib/views/pages/matching/matching_choose_page.dart
  lib/views/pages/signup/signup_email.dart
  lib/views/pages/signup/signup_emailverify.dart
  lib/views/pages/start_page.dart
Labels: 🔧fix

#89 Feat/#76 real time chat
  assets/character/vsGame_button.png
  assets/character/vsGame_hands.png
  lib/apis/apis.dart
  lib/apis/firebase_apis.dart
  lib/main.dart
  lib/models/vsGames.dart
  lib/repository/sql_message_repository.dart
  lib/views/components/matching_chatting_widget.dart
  lib/views/components/message_bubble_widget.dart
  lib/views/pages/chatting/chatting_page.dart
  lib/views/pages/home_page.dart
  lib/views/pages/matching/matching_state_page.dart
  lib/views/pages/setting/setting_delete_done_page.dart
  lib/views/pages/setting/setting_edit_PW_done_page.dart
  lib/views/pages/signup/signup_emailverify.dart
  lib/views/pages/splash_page.dart
Labels: 🌟feat, 🔧fix

#106 Feat/#101 market
  assets/translations/en-US.json
  assets/translations/ko-KR.json
  lib/main.dart
  lib/models/market_articles.dart
  lib/views/components/board_drawer_widget.dart
  lib/views/pages/board/market_board_page.dart
  lib/views/pages/board/market_notice_page.dart
  lib/views/pages/board/market_posting_board_page.dart
  pubspec.lock
  pubspec.yaml
Labels: 🌟feat

#112 Fix/#104 v1 feedback
  assets/icon/ICON_board.svg
  assets/icon/ICON_down.svg
  assets/icon/ICON_good.svg
  assets/icon/ICON_list.svg
  assets/icon/ICON_more.svg
  assets/icon/ICON_my_post.svg
  assets/icon/ICON_notice.svg
  assets/icon/ICON_notification.svg
  assets/icon/ICON_photo_1.png
  assets/icon/ICON_photo_2.svg
  assets/icon/ICON_post.svg
  assets/icon/ICON_reply.svg
  assets/icon/ICON_send.svg
  assets/icon/ICON_won.svg
  assets/icon/icon_add_photo.svg
  assets/icon/icon_comment.svg
  assets/icon/icon_more.svg
  assets/icon/icon_search.svg
  assets/icon/icon_send.svg
  assets/translations/en-US.json
  assets/translations/ko-KR.json
  ios/Runner/GoogleService-Info.plist
  lib/apis/apis.dart
  lib/views/components/article_widget.dart
  lib/views/components/board_drawer_widget.dart
  lib/views/components/board_tab_widget.dart
  lib/views/components/chatting_button_widget.dart
  lib/views/components/info_article_widget.dart
  lib/views/components/matching_button_widget.dart
  lib/views/components/report_iOS_dialog_widget.dart
  lib/views/components/setting_list_widget.dart
  lib/views/components/total_article_widget.dart
  lib/views/pages/board/article_page.dart
  lib/views/pages/board/article_writing_page.dart
  lib/views/pages/board/fashion_board_page.dart
  lib/views/pages/board/food_board_page.dart
  lib/views/pages/board/free_posting_board_page.dart
  lib/views/pages/board/game_board_page.dart
  lib/views/pages/board/info_article_page.dart
  lib/views/pages/board/info_board_page.dart
  lib/views/pages/board/market_board_page.dart
  lib/views/pages/board/market_notice_page.dart
  lib/views/pages/board/market_posting_board_page.dart
  lib/views/pages/board/music_board_page.dart
  lib/views/pages/home_page.dart
  lib/views/pages/signup/signup_birthday.dart
  lib/views/pages/signup/signup_name.dart
  lib/views/pages/signup/signup_nationality.dart
Labels: 🌟feat, 🔧fix
