Repository 4Ailen/frontend, pull requests merged in 2023-07, with the labels that each got.

#75 Feat/#69 matched user
  android/app/google-services.json
  assets/translations/en-US.json
  assets/translations/ko-KR.json
  ios/Podfile.lock
  lib/apis/apis.dart
  lib/apis/firebase_apis.dart
  lib/main.dart
  lib/mockdatas/mockdata_model.dart
  lib/models/chatRoom_model.dart
  lib/models/countries.dart
  lib/models/message_model.dart
  lib/models/partner_model.dart
  lib/models/room_model.dart
  lib/models/signup_model.dart
  lib/providers/chat_provider.dart
  lib/repository/sql_message_database.dart
  lib/repository/sql_message_repository.dart
  lib/views/components/matching_chatting_widget.dart
  lib/views/components/message_bubble_widget.dart
  lib/views/components/profileDialog_widget.dart
  lib/views/pages/chatting/chatting_page.dart
  lib/views/pages/home_page.dart
  lib/views/pages/loading_page.dart
  lib/views/pages/matching/matching_done_page.dart
  lib/views/pages/matching/matching_list_page.dart
  lib/views/pages/signup/signup_name.dart
  lib/views/pages/signup/signup_nationality.dart
  lib/views/pages/signup/signup_password.dart
  lib/views/pages/splash_page.dart
  lib/views/pages/start_page.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: 🌟feat

#78 Feat/#76 chat token 채팅 인증 로직 추가
  lib/apis/apis.dart
  lib/mockdatas/mockdata_model.dart
  lib/views/pages/chatting/chatting_page.dart
  lib/views/pages/login/login_page.dart
Labels: 🌟feat, 천천히 리뷰해주세요~

#79 Feat/#76 websocket response 웹소켓 응답 수신 로직 변경
  lib/mockdatas/mockdata_model.dart
  lib/views/pages/chatting/chatting_page.dart
Labels: 🌟feat, 🔧fix, 꼼꼼히 리뷰부탁드려요!
